Traceback (most recent call last):
  File "/Users/mpettyjo/anaconda3/envs/ddenv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mpettyjo/anaconda3/envs/ddenv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mpettyjo/anaconda3/envs/ddenv/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mpettyjo/anaconda3/envs/ddenv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/mpettyjo/anaconda3/envs/ddenv/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/mpettyjo/anaconda3/envs/ddenv/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/mpettyjo/anaconda3/envs/ddenv/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mpettyjo/anaconda3/envs/ddenv/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib widget
def single_variable_plot_widget(variable_option, buckets_option):
    labels_list = {'body mass': 'Body Mass (kilograms)', 
              'brain size': 'Brain Size (kilograms)',
              'metabolic rate': 'Metabolic Rate (energy/kilogram)'}
    label = labels_list[variable_option]

    plt.hist(df[variable_option], bins=int(buckets_option))
    plt.xlabel(label)
    plt.ylabel("Frequency")
    plt.title(f"Distribution of {label}")
    plt.show()

variable_widget = widgets.Dropdown(options=['body mass', 'brain size', 'metabolic rate'], 
                                   description='Choose a variable to plot:')

buckets_widget = widgets.FloatText(value=20,
                                description='Enter the number of buckets to divide your data into:',
                                disabled=False)

widgets.interact(single_variable_plot_widget, variable_option=variable_widget, buckets_option=buckets_widget)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
File [0;32m~/anaconda3/envs/ddenv/lib/python3.10/site-packages/matplotlib/backends/registry.py:407[0m, in [0;36mBackendRegistry.resolve_gui_or_backend[0;34m(self, gui_or_backend)[0m
[1;32m    406[0m [38;5;28;01mtry[39;00m:
[0;32m--> 407[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mresolve_backend[49m[43m([49m[43mgui_or_backend[49m[43m)[49m
[1;32m    408[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:  [38;5;66;03m# KeyError ?[39;00m

File [0;32m~/anaconda3/envs/ddenv/lib/python3.10/site-packages/matplotlib/backends/registry.py:369[0m, in [0;36mBackendRegistry.resolve_backend[0;34m(self, backend)[0m
[1;32m    368[0m [38;5;28;01mif[39;00m gui [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 369[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124m'[39m[38;5;132;01m{[39;00mbackend[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m is not a recognised backend name[39m[38;5;124m"[39m)
[1;32m    371[0m [38;5;28;01mreturn[39;00m backend, gui [38;5;28;01mif[39;00m gui [38;5;241m!=[39m [38;5;124m"[39m[38;5;124mheadless[39m[38;5;124m"[39m [38;5;28;01melse[39;00m [38;5;28;01mNone[39;00m

[0;31mRuntimeError[0m: 'widget' is not a recognised backend name

During handling of the above exception, another exception occurred:

[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[5], line 1[0m
[0;32m----> 1[0m [43mget_ipython[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mrun_line_magic[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mmatplotlib[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mwidget[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21msingle_variable_plot_widget[39m(variable_option, buckets_option):
[1;32m      3[0m     labels_list [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mbody mass[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124mBody Mass (kilograms)[39m[38;5;124m'[39m, 
[1;32m      4[0m               [38;5;124m'[39m[38;5;124mbrain size[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124mBrain Size (kilograms)[39m[38;5;124m'[39m,
[1;32m      5[0m               [38;5;124m'[39m[38;5;124mmetabolic rate[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124mMetabolic Rate (energy/kilogram)[39m[38;5;124m'[39m}

File [0;32m~/anaconda3/envs/ddenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2482[0m, in [0;36mInteractiveShell.run_line_magic[0;34m(self, magic_name, line, _stack_depth)[0m
[1;32m   2480[0m     kwargs[[38;5;124m'[39m[38;5;124mlocal_ns[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_local_scope(stack_depth)
[1;32m   2481[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[0;32m-> 2482[0m     result [38;5;241m=[39m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   2484[0m [38;5;66;03m# The code below prevents the output from being displayed[39;00m
[1;32m   2485[0m [38;5;66;03m# when using magics with decorator @output_can_be_silenced[39;00m
[1;32m   2486[0m [38;5;66;03m# when the last Python token in the expression is a ';'.[39;00m
[1;32m   2487[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(fn, magic[38;5;241m.[39mMAGIC_OUTPUT_CAN_BE_SILENCED, [38;5;28;01mFalse[39;00m):

File [0;32m~/anaconda3/envs/ddenv/lib/python3.10/site-packages/IPython/core/magics/pylab.py:103[0m, in [0;36mPylabMagics.matplotlib[0;34m(self, line)[0m
[1;32m     98[0m     [38;5;28mprint[39m(
[1;32m     99[0m         [38;5;124m"[39m[38;5;124mAvailable matplotlib backends: [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m
[1;32m    100[0m         [38;5;241m%[39m _list_matplotlib_backends_and_gui_loops()
[1;32m    101[0m     )
[1;32m    102[0m [38;5;28;01melse[39;00m:
[0;32m--> 103[0m     gui, backend [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mshell[49m[38;5;241;43m.[39;49m[43menable_matplotlib[49m[43m([49m[43margs[49m[38;5;241;43m.[39;49m[43mgui[49m[43m)[49m
[1;32m    104[0m     [38;5;28mself[39m[38;5;241m.[39m_show_matplotlib_backend(args[38;5;241m.[39mgui, backend)

File [0;32m~/anaconda3/envs/ddenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3667[0m, in [0;36mInteractiveShell.enable_matplotlib[0;34m(self, gui)[0m
[1;32m   3664[0m     [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mmatplotlib_inline[39;00m[38;5;21;01m.[39;00m[38;5;21;01mbackend_inline[39;00m
[1;32m   3666[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m pylabtools [38;5;28;01mas[39;00m pt
[0;32m-> 3667[0m gui, backend [38;5;241m=[39m [43mpt[49m[38;5;241;43m.[39;49m[43mfind_gui_and_backend[49m[43m([49m[43mgui[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpylab_gui_select[49m[43m)[49m
[1;32m   3669[0m [38;5;28;01mif[39;00m gui [38;5;241m!=[39m [38;5;28;01mNone[39;00m:
[1;32m   3670[0m     [38;5;66;03m# If we have our first gui selection, store it[39;00m
[1;32m   3671[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mpylab_gui_select [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

File [0;32m~/anaconda3/envs/ddenv/lib/python3.10/site-packages/IPython/core/pylabtools.py:349[0m, in [0;36mfind_gui_and_backend[0;34m(gui, gui_select)[0m
[1;32m    347[0m [38;5;28;01melse[39;00m:
[1;32m    348[0m     gui [38;5;241m=[39m _convert_gui_to_matplotlib(gui)
[0;32m--> 349[0m     backend, gui [38;5;241m=[39m [43mbackend_registry[49m[38;5;241;43m.[39;49m[43mresolve_gui_or_backend[49m[43m([49m[43mgui[49m[43m)[49m
[1;32m    351[0m gui [38;5;241m=[39m _convert_gui_from_matplotlib(gui)
[1;32m    352[0m [38;5;28;01mreturn[39;00m gui, backend

File [0;32m~/anaconda3/envs/ddenv/lib/python3.10/site-packages/matplotlib/backends/registry.py:409[0m, in [0;36mBackendRegistry.resolve_gui_or_backend[0;34m(self, gui_or_backend)[0m
[1;32m    407[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mresolve_backend(gui_or_backend)
[1;32m    408[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:  [38;5;66;03m# KeyError ?[39;00m
[0;32m--> 409[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(
[1;32m    410[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124m'[39m[38;5;132;01m{[39;00mgui_or_backend[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m is not a recognised GUI loop or backend name[39m[38;5;124m"[39m)

[0;31mRuntimeError[0m: 'widget' is not a recognised GUI loop or backend name

